#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="${PROJECT_DIR:-/home/ProjmanagerPy}"
CRON_FILE="${CRON_FILE:-/etc/cron.d/projmanager-postgres-backup}"
BACKUP_SCRIPT="$PROJECT_DIR/scripts/backup_postgres.sh"
CRON_SCHEDULE="${CRON_SCHEDULE:-0 2 * * *}"
RETENTION_DAYS="${RETENTION_DAYS:-14}"

if [ "$(id -u)" -ne 0 ]; then
  echo "Execute este script como root ou com sudo." >&2
  exit 1
fi
if [ ! -x "$BACKUP_SCRIPT" ]; then
  echo "Backup script not found or not executable: $BACKUP_SCRIPT" >&2
  exit 1
fi
if ! [[ "$RETENTION_DAYS" =~ ^[0-9]+$ ]]; then
  echo "RETENTION_DAYS must be a non-negative integer" >&2
  exit 1
fi

cat > "$CRON_FILE" <<EOF
# ProjmanagerPy PostgreSQL backup — generated by configurar_backup_cron.sh
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
$CRON_SCHEDULE root PROJECT_DIR='$PROJECT_DIR' RETENTION_DAYS='$RETENTION_DAYS' '$BACKUP_SCRIPT' >> '$PROJECT_DIR/backups/backup.log' 2>&1
EOF
chmod 0644 "$CRON_FILE"

if command -v systemctl >/dev/null 2>&1; then
  if systemctl list-unit-files cron.service >/dev/null 2>&1; then
    systemctl enable --now cron.service >/dev/null 2>&1 || true
  elif systemctl list-unit-files crond.service >/dev/null 2>&1; then
    systemctl enable --now crond.service >/dev/null 2>&1 || true
  fi
fi

printf 'Cron configured: %s\n' "$CRON_FILE"
printf 'Schedule: %s UTC/server local time\n' "$CRON_SCHEDULE"
printf 'Retention: %s days\n' "$RETENTION_DAYS"
cat "$CRON_FILE"
