// Paleta de 256 cores nomeadas para "Cor do projeto" — mesma lista do
// backend (ver app/color_palette.py; mantidas em sincronia manualmente,
// os dois arquivos raramente mudam). Cada `project.color` vindo da API é
// um hex fixo (ex.: "#2A78D6"), não mais uma chave "series-N" resolvida
// via variável CSS clara/escura — por isso a cor do projeto não se ajusta
// mais sozinha entre os temas claro/escuro (trade-off aceito ao trocar
// pela paleta maior).
export const PROJECT_COLOR_PALETTE = [
  { id: 0, name: 'Preto Puro', hex: '#000000' },
  { id: 1, name: 'Bordô Escuro', hex: '#800000' },
  { id: 2, name: 'Verde Escuro', hex: '#008000' },
  { id: 3, name: 'Oliveira Escuro', hex: '#808000' },
  { id: 4, name: 'Azul Marinho', hex: '#000080' },
  { id: 5, name: 'Roxo Escuro', hex: '#800080' },
  { id: 6, name: 'Azul Petróleo Escuro', hex: '#008080' },
  { id: 7, name: 'Prata / Cinza Claro', hex: '#C0C0C0' },
  { id: 8, name: 'Cinza Médio', hex: '#808080' },
  { id: 9, name: 'Vermelho Vivo', hex: '#FF0000' },
  { id: 10, name: 'Verde Limão Vivo', hex: '#00FF00' },
  { id: 11, name: 'Amarelo Puro', hex: '#FFFF00' },
  { id: 12, name: 'Azul Elétrico', hex: '#0000FF' },
  { id: 13, name: 'Magenta Vivo', hex: '#FF00FF' },
  { id: 14, name: 'Ciano / Azul Turquesa Vivo', hex: '#00FFFF' },
  { id: 15, name: 'Branco Puro', hex: '#FFFFFF' },
  { id: 16, name: 'Preto Profundo', hex: '#000000' },
  { id: 17, name: 'Azul Noturno Profundo', hex: '#00005F' },
  { id: 18, name: 'Azul Marinho Escuro', hex: '#000087' },
  { id: 19, name: 'Azul Royal Escuro', hex: '#0000AF' },
  { id: 20, name: 'Azul Royal Intermediário', hex: '#0000D7' },
  { id: 21, name: 'Azul Brilhante', hex: '#0000FF' },
  { id: 22, name: 'Verde Floresta Escuro', hex: '#005F00' },
  { id: 23, name: 'Verde Petróleo Escuro', hex: '#005F5F' },
  { id: 24, name: 'Azul Pavão Escuro', hex: '#005F87' },
  { id: 25, name: 'Azul Acinzentado Escuro', hex: '#005FAF' },
  { id: 26, name: 'Azul Céu Escuro', hex: '#005FD7' },
  { id: 27, name: 'Azul Turquesa Escuro', hex: '#005FFF' },
  { id: 28, name: 'Verde Folha Escuro', hex: '#008700' },
  { id: 29, name: 'Verde Menta Escuro', hex: '#00875F' },
  { id: 30, name: 'Verde Água Escuro', hex: '#008787' },
  { id: 31, name: 'Azul Petróleo Médio', hex: '#0087AF' },
  { id: 32, name: 'Azul Claro Profundo', hex: '#0087D7' },
  { id: 33, name: 'Azul Celeste Médio', hex: '#0087FF' },
  { id: 34, name: 'Verde Folha Médio', hex: '#00AF00' },
  { id: 35, name: 'Verde Esmeralda Escuro', hex: '#00AF5F' },
  { id: 36, name: 'Verde Água Médio', hex: '#00AF87' },
  { id: 37, name: 'Verde Turquesa', hex: '#00AFAF' },
  { id: 38, name: 'Azul Turquesa Médio', hex: '#00AFD7' },
  { id: 39, name: 'Azul Céu Brilhante', hex: '#00AFFF' },
  { id: 40, name: 'Verde Grama', hex: '#00D700' },
  { id: 41, name: 'Verde Esmeralda', hex: '#00D75F' },
  { id: 42, name: 'Verde Água Claro', hex: '#00D787' },
  { id: 43, name: 'Verde Água Brilhante', hex: '#00D7AF' },
  { id: 44, name: 'Turquesa Claro', hex: '#00D7D7' },
  { id: 45, name: 'Azul Turquesa Claro', hex: '#00D7FF' },
  { id: 46, name: 'Verde Limão Puro', hex: '#00FF00' },
  { id: 47, name: 'Verde Claro Vibrante', hex: '#00FF5F' },
  { id: 48, name: 'Verde Menta Brilhante', hex: '#00FF87' },
  { id: 49, name: 'Verde Água Pastel', hex: '#00FFAF' },
  { id: 50, name: 'Ciano Pastel', hex: '#00FFD7' },
  { id: 51, name: 'Ciano Brilhante', hex: '#00FFFF' },
  { id: 52, name: 'Vermelho Escuro Profundo', hex: '#5F0000' },
  { id: 53, name: 'Roxo Escuro Profundo', hex: '#5F005F' },
  { id: 54, name: 'Roxo Acinzentado Escuro', hex: '#5F0087' },
  { id: 55, name: 'Roxo Violeta Escuro', hex: '#5F00AF' },
  { id: 56, name: 'Roxo Azulado Escuro', hex: '#5F00D7' },
  { id: 57, name: 'Azul Violeta Escuro', hex: '#5F00FF' },
  { id: 58, name: 'Marrom Oliva Escuro', hex: '#5F5F00' },
  { id: 59, name: 'Cinza Escuro Chumbo', hex: '#5F5F5F' },
  { id: 60, name: 'Azul Aço Escuro', hex: '#5F5F87' },
  { id: 61, name: 'Azul Lavanda Escuro', hex: '#5F5FAF' },
  { id: 62, name: 'Azul Perolado Escuro', hex: '#5F5FD7' },
  { id: 63, name: 'Azul Pastel Escuro', hex: '#5F5FFF' },
  { id: 64, name: 'Verde Oliva Médio', hex: '#5F8700' },
  { id: 65, name: 'Verde Musgo Escuro', hex: '#5F875F' },
  { id: 66, name: 'Verde Cinzento Escuro', hex: '#5F8787' },
  { id: 67, name: 'Azul Petróleo Suave', hex: '#5F87AF' },
  { id: 68, name: 'Azul Aço Médio', hex: '#5F87D7' },
  { id: 69, name: 'Azul Céu Suave', hex: '#5F87FF' },
  { id: 70, name: 'Verde Oliva Claro', hex: '#5FAF00' },
  { id: 71, name: 'Verde Musgo Médio', hex: '#5FAF5F' },
  { id: 72, name: 'Verde Água Suave', hex: '#5FAF87' },
  { id: 73, name: 'Verde Turquesa Suave', hex: '#5FAFAF' },
  { id: 74, name: 'Azul Pastel Suave', hex: '#5FAFD7' },
  { id: 75, name: 'Azul Claro Pastel', hex: '#5FAFFF' },
  { id: 76, name: 'Verde Amarelado Médio', hex: '#5FD700' },
  { id: 77, name: 'Verde Limão Suave', hex: '#5FD75F' },
  { id: 78, name: 'Verde Menta Suave', hex: '#5FD787' },
  { id: 79, name: 'Verde Água Pastel Claro', hex: '#5FD7AF' },
  { id: 80, name: 'Ciano Suave', hex: '#5FD7D7' },
  { id: 81, name: 'Azul Gelo Suave', hex: '#5FD7FF' },
  { id: 82, name: 'Verde Lima Brilhante', hex: '#5FFF00' },
  { id: 83, name: 'Verde Claro Pastel', hex: '#5FFF5F' },
  { id: 84, name: 'Verde Menta Claro', hex: '#5FFF87' },
  { id: 85, name: 'Verde Água Claro Pastel', hex: '#5FFFAF' },
  { id: 86, name: 'Ciano Claro Pastel', hex: '#5FFFD7' },
  { id: 87, name: 'Azul Gelo Claro', hex: '#5FFFFF' },
  { id: 88, name: 'Vermelho Escuro Intenso', hex: '#870000' },
  { id: 89, name: 'Vinho Escuro', hex: '#87005F' },
  { id: 90, name: 'Roxo Vinho Escuro', hex: '#870087' },
  { id: 91, name: 'Roxo Escuro Intenso', hex: '#8700AF' },
  { id: 92, name: 'Roxo Violeta Intenso', hex: '#8700D7' },
  { id: 93, name: 'Roxo Azulado Intenso', hex: '#8700FF' },
  { id: 94, name: 'Marrom Escuro', hex: '#875F00' },
  { id: 95, name: 'Marrom Acinzentado Escuro', hex: '#875F5F' },
  { id: 96, name: 'Roxo Acinzentado Médio', hex: '#875F87' },
  { id: 97, name: 'Roxo Lavanda Escuro', hex: '#875FAF' },
  { id: 98, name: 'Roxo Azulado Médio', hex: '#875FD7' },
  { id: 99, name: 'Azul Lavanda Médio', hex: '#875FFF' },
  { id: 100, name: 'Marrom Oliva Médio', hex: '#878700' },
  { id: 101, name: 'Verde Oliva Acinzentado', hex: '#87875F' },
  { id: 102, name: 'Cinza Médio Chumbo', hex: '#878787' },
  { id: 103, name: 'Cinza Azulado Médio', hex: '#8787AF' },
  { id: 104, name: 'Azul Aço Claro', hex: '#8787D7' },
  { id: 105, name: 'Azul Lavanda Claro', hex: '#8787FF' },
  { id: 106, name: 'Verde Oliva Dourado', hex: '#87AF00' },
  { id: 107, name: 'Verde Musgo Claro', hex: '#87AF5F' },
  { id: 108, name: 'Verde Acinzentado Claro', hex: '#87AF87' },
  { id: 109, name: 'Verde Água Cinzento', hex: '#87AFAF' },
  { id: 110, name: 'Azul Pastel Médio', hex: '#87AFD7' },
  { id: 111, name: 'Azul Gelo Médio', hex: '#87AFFF' },
  { id: 112, name: 'Verde Amarelado Claro', hex: '#87D700' },
  { id: 113, name: 'Verde Limão Pastel', hex: '#87D75F' },
  { id: 114, name: 'Verde Menta Pastel', hex: '#87D787' },
  { id: 115, name: 'Verde Água Pastel Suave', hex: '#87D7AF' },
  { id: 116, name: 'Ciano Pastel Suave', hex: '#87D7D7' },
  { id: 117, name: 'Azul Céu Pastel Suave', hex: '#87D7FF' },
  { id: 118, name: 'Verde Limão Fluorescente', hex: '#87FF00' },
  { id: 119, name: 'Verde Limão Brilhante Suave', hex: '#87FF5F' },
  { id: 120, name: 'Verde Menta Brilhante Suave', hex: '#87FF87' },
  { id: 121, name: 'Verde Água Brilhante Suave', hex: '#87FFAF' },
  { id: 122, name: 'Ciano Brilhante Suave', hex: '#87FFD7' },
  { id: 123, name: 'Azul Gelo Brilhante Suave', hex: '#87FFFF' },
  { id: 124, name: 'Vermelho Tijolo Escuro', hex: '#AF0000' },
  { id: 125, name: 'Vinho Médio', hex: '#AF005F' },
  { id: 126, name: 'Magenta Escuro Intenso', hex: '#AF0087' },
  { id: 127, name: 'Roxo Magenta Escuro', hex: '#AF00AF' },
  { id: 128, name: 'Roxo Claro Intenso', hex: '#AF00D7' },
  { id: 129, name: 'Roxo Azulado Claro', hex: '#AF00FF' },
  { id: 130, name: 'Marrom Claro', hex: '#AF5F00' },
  { id: 131, name: 'Marrom Rosado Escuro', hex: '#AF5F5F' },
  { id: 132, name: 'Roxo Rosado Escuro', hex: '#AF5F87' },
  { id: 133, name: 'Roxo Violeta Médio', hex: '#AF5FAF' },
  { id: 134, name: 'Roxo Lavanda Claro', hex: '#AF5FD7' },
  { id: 135, name: 'Roxo Azulado Pastel', hex: '#AF5FFF' },
  { id: 136, name: 'Marrom Dourado Escuro', hex: '#AF8700' },
  { id: 137, name: 'Marrom Acinzentado Médio', hex: '#AF875F' },
  { id: 138, name: 'Marrom Rosado Médio', hex: '#AF8787' },
  { id: 139, name: 'Roxo Acinzentado Claro', hex: '#AF87AF' },
  { id: 140, name: 'Roxo Lavanda Pastel', hex: '#AF87D7' },
  { id: 141, name: 'Azul Lavanda Pastel', hex: '#AF87FF' },
  { id: 142, name: 'Amarelo Oliva Escuro', hex: '#AFAF00' },
  { id: 143, name: 'Verde Oliva Claro Médio', hex: '#AFAF5F' },
  { id: 144, name: 'Verde Acinzentado Médio', hex: '#AFAF87' },
  { id: 145, name: 'Cinza Esverdeado Médio', hex: '#AFAFAF' },
  { id: 146, name: 'Cinza Azulado Claro', hex: '#AFAFD7' },
  { id: 147, name: 'Azul Gelo Pastel', hex: '#AFAFFF' },
  { id: 148, name: 'Verde Oliva Amarelado', hex: '#AFD700' },
  { id: 149, name: 'Verde Amarelado Pastel', hex: '#AFD75F' },
  { id: 150, name: 'Verde Oliva Pastel', hex: '#AFD787' },
  { id: 151, name: 'Verde Musgo Pastel', hex: '#AFD7AF' },
  { id: 152, name: 'Verde Água Pastel Claro', hex: '#AFD7D7' },
  { id: 153, name: 'Azul Céu Pastel Claro', hex: '#AFD7FF' },
  { id: 154, name: 'Verde Limão Claro Intenso', hex: '#AFFF00' },
  { id: 155, name: 'Verde Limão Pastel Claro', hex: '#AFFF5F' },
  { id: 156, name: 'Verde Menta Pastel Claro', hex: '#AFFF87' },
  { id: 157, name: 'Verde Água Pastel Claro 2', hex: '#AFFFAF' },
  { id: 158, name: 'Ciano Pastel Claro', hex: '#AFFFD7' },
  { id: 159, name: 'Azul Gelo Pastel Claro', hex: '#AFFFFF' },
  { id: 160, name: 'Vermelho Vivo Escuro', hex: '#D70000' },
  { id: 161, name: 'Magenta Escuro Vivo', hex: '#D7005F' },
  { id: 162, name: 'Magenta Escuro', hex: '#D70087' },
  { id: 163, name: 'Roxo Magenta Médio', hex: '#D700AF' },
  { id: 164, name: 'Roxo Magenta Claro', hex: '#D700D7' },
  { id: 165, name: 'Roxo Magenta Brilhante', hex: '#D700FF' },
  { id: 166, name: 'Laranja Escuro', hex: '#D75F00' },
  { id: 167, name: 'Vermelho Rosado Médio', hex: '#D75F5F' },
  { id: 168, name: 'Rosa Escuro Intenso', hex: '#D75F87' },
  { id: 169, name: 'Rosa Violeta Médio', hex: '#D75FAF' },
  { id: 170, name: 'Rosa Violeta Claro', hex: '#D75FD7' },
  { id: 171, name: 'Magenta Pastel Brilhante', hex: '#D75FFF' },
  { id: 172, name: 'Laranja Amarelado Escuro', hex: '#D78700' },
  { id: 173, name: 'Marrom Laranja Claro', hex: '#D7875F' },
  { id: 174, name: 'Rosa Pastel Escuro', hex: '#D78787' },
  { id: 175, name: 'Rosa Lilás Escuro', hex: '#D787AF' },
  { id: 176, name: 'Lilás Claro', hex: '#D787D7' },
  { id: 177, name: 'Lilás Azulado Claro', hex: '#D787FF' },
  { id: 178, name: 'Amarelo Dourado Escuro', hex: '#D7AF00' },
  { id: 179, name: 'Amarelo Laranja Pastel', hex: '#D7AF5F' },
  { id: 180, name: 'Marrom Amarelado Claro', hex: '#D7AF87' },
  { id: 181, name: 'Beige Rosado', hex: '#D7AFAF' },
  { id: 182, name: 'Rosa Pastel Claro', hex: '#D7AFD7' },
  { id: 183, name: 'Lilás Pastel Claro', hex: '#D7AFFF' },
  { id: 184, name: 'Amarelo Oliva Brilhante', hex: '#D7D700' },
  { id: 185, name: 'Amarelo Esverdeado Pastel', hex: '#D7D75F' },
  { id: 186, name: 'Verde Oliva Pastel Claro', hex: '#D7D787' },
  { id: 187, name: 'Verde Musgo Pastel Claro', hex: '#D7D7AF' },
  { id: 188, name: 'Cinza Esverdeado Claro', hex: '#D7D7D7' },
  { id: 189, name: 'Azul Gelo Pastel Claro 2', hex: '#D7D7FF' },
  { id: 190, name: 'Amarelo Limão Brilhante', hex: '#D7FF00' },
  { id: 191, name: 'Amarelo Limão Pastel', hex: '#D7FF5F' },
  { id: 192, name: 'Verde Amarelado Brilhante', hex: '#D7FF87' },
  { id: 193, name: 'Verde Limão Brilhante Claro', hex: '#D7FFAF' },
  { id: 194, name: 'Verde Menta Brilhante Claro', hex: '#D7FFD7' },
  { id: 195, name: 'Ciano Brilhante Claro', hex: '#D7FFFF' },
  { id: 196, name: 'Vermelho Puro Brilhante', hex: '#FF0000' },
  { id: 197, name: 'Rosa Pink Intenso', hex: '#FF005F' },
  { id: 198, name: 'Magenta Vivo Brilhante', hex: '#FF0087' },
  { id: 199, name: 'Magenta Puro', hex: '#FF00AF' },
  { id: 200, name: 'Magenta Claro Brilhante', hex: '#FF00D7' },
  { id: 201, name: 'Magenta Neons', hex: '#FF00FF' },
  { id: 202, name: 'Laranja Puro', hex: '#FF5F00' },
  { id: 203, name: 'Vermelho Laranja Vivo', hex: '#FF5F5F' },
  { id: 204, name: 'Rosa Pink Vivo', hex: '#FF5F87' },
  { id: 205, name: 'Rosa Magenta Claro', hex: '#FF5FAF' },
  { id: 206, name: 'Rosa Lilás Vivo', hex: '#FF5FD7' },
  { id: 207, name: 'Magenta Pastel Vivo', hex: '#FF5FFF' },
  { id: 208, name: 'Laranja Forte', hex: '#FF8700' },
  { id: 209, name: 'Laranja Claro Vivo', hex: '#FF875F' },
  { id: 210, name: 'Rosa Salmão Vivo', hex: '#FF8787' },
  { id: 211, name: 'Rosa Pastel Intenso', hex: '#FF87AF' },
  { id: 212, name: 'Rosa Lilás Pastel', hex: '#FF87D7' },
  { id: 213, name: 'Lilás Brilhante', hex: '#FF87FF' },
  { id: 214, name: 'Amarelo Ouro Vivo', hex: '#FFAF00' },
  { id: 215, name: 'Laranja Amarelado Pastel', hex: '#FFAF5F' },
  { id: 216, name: 'Laranja Salmão Pastel', hex: '#FFAF87' },
  { id: 217, name: 'Rosa Salmão Claro', hex: '#FFAFAF' },
  { id: 218, name: 'Rosa Bebe Brilhante', hex: '#FFAFD7' },
  { id: 219, name: 'Rosa Lilás Claro', hex: '#FFAFFF' },
  { id: 220, name: 'Amarelo Ouro Brilhante', hex: '#FFD700' },
  { id: 221, name: 'Amarelo Laranja Brilhante', hex: '#FFD75F' },
  { id: 222, name: 'Amarelo Pastel Brilhante', hex: '#FFD787' },
  { id: 223, name: 'Amarelo Creme Brilhante', hex: '#FFD7AF' },
  { id: 224, name: 'Rosa Creme Claro', hex: '#FFD7D7' },
  { id: 225, name: 'Rosa Pastel Neve', hex: '#FFD7FF' },
  { id: 226, name: 'Amarelo Puro Brilhante', hex: '#FFFF00' },
  { id: 227, name: 'Amarelo Claro Brilhante', hex: '#FFFF5F' },
  { id: 228, name: 'Amarelo Pastel Claro', hex: '#FFFF87' },
  { id: 229, name: 'Amarelo Gelo', hex: '#FFFFAF' },
  { id: 230, name: 'Amarelo Neve', hex: '#FFFFD7' },
  { id: 231, name: 'Branco Puro Neve', hex: '#FFFFFF' },
  { id: 232, name: 'Cinza Quase Preto 1', hex: '#080808' },
  { id: 233, name: 'Cinza Quase Preto 2', hex: '#121212' },
  { id: 234, name: 'Cinza Grafite Escuro', hex: '#1C1C1C' },
  { id: 235, name: 'Cinza Chumbo Escuro', hex: '#262626' },
  { id: 236, name: 'Cinza Escuro 1', hex: '#303030' },
  { id: 237, name: 'Cinza Escuro 2', hex: '#3A3A3A' },
  { id: 238, name: 'Cinza Médio Escuro 1', hex: '#444444' },
  { id: 239, name: 'Cinza Médio Escuro 2', hex: '#4E4E4E' },
  { id: 240, name: 'Cinza Médio 1', hex: '#585858' },
  { id: 241, name: 'Cinza Médio 2', hex: '#626262' },
  { id: 242, name: 'Cinza Médio 3', hex: '#6C6C6C' },
  { id: 243, name: 'Cinza Médio 4', hex: '#767676' },
  { id: 244, name: 'Cinza Claro 1', hex: '#808080' },
  { id: 245, name: 'Cinza Claro 2', hex: '#8A8A8A' },
  { id: 246, name: 'Cinza Claro 3', hex: '#949494' },
  { id: 247, name: 'Cinza Claro 4', hex: '#9E9E9E' },
  { id: 248, name: 'Cinza Prata 1', hex: '#A8A8A8' },
  { id: 249, name: 'Cinza Prata 2', hex: '#B2B2B2' },
  { id: 250, name: 'Cinza Muito Claro 1', hex: '#BCBCBC' },
  { id: 251, name: 'Cinza Muito Claro 2', hex: '#C6C6C6' },
  { id: 252, name: 'Cinza Gelo 1', hex: '#D0D0D0' },
  { id: 253, name: 'Cinza Gelo 2', hex: '#DADADA' },
  { id: 254, name: 'Cinza Brilhante', hex: '#E4E4E4' },
  { id: 255, name: 'Branco Neve', hex: '#EEEEEE' },
]

// Mesmo default do backend (ver app/color_palette.py) — precisa ser um hex
// que exista de fato na lista acima.
export const DEFAULT_PROJECT_COLOR = '#5F87D7'

// Nome de exibição pra um hex (primeira entrada que bate, já que alguns
// hexes se repetem com ids diferentes — ex.: "#000000" tem os ids 0 e 16).
// Sem correspondência (cor legada não migrada, ou valor inesperado), cai
// no próprio hex como rótulo.
export function colorNameFor(hex) {
  if (!hex) return ''
  const normalized = hex.toUpperCase()
  return PROJECT_COLOR_PALETTE.find((entry) => entry.hex === normalized)?.name || hex
}

// Preto ou branco, o que tiver mais contraste sobre `hex` — necessário
// agora que a cor do projeto pode ser qualquer uma das 256 (incluindo
// tons bem claros, tipo "Branco Neve"), onde texto branco fixo (como era
// com as 8 cores antigas, todas escuras o bastante) ficaria ilegível.
// Fórmula de luminância perceptual (YIQ), não a fórmula completa do WCAG —
// precisão de sobra pra só decidir "claro ou escuro".
export function contrastTextColor(hex) {
  if (!hex || hex.length < 7) return '#FFFFFF'
  const r = parseInt(hex.slice(1, 3), 16)
  const g = parseInt(hex.slice(3, 5), 16)
  const b = parseInt(hex.slice(5, 7), 16)
  const yiq = (r * 299 + g * 587 + b * 114) / 1000
  return yiq >= 150 ? '#000000' : '#FFFFFF'
}
